name: ECS AWS Deployment

# This is a reusable workflow for Docker builds and AWS deployments
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
      AWS_ROLE_TO_ASSUME:
        description: 'AWS role to assume for OIDC'
        required: true
        type: string
      AWS_REGION:
        description: 'AWS region'
        required: true
        type: string
      DOPPLER_DOWNLOAD_SECRETS:
        description: 'Download Doppler secrets'
        required: false
        default: false  
        type: boolean
      VERSION_VARIABLE_NAME:
        description: 'Version variable name'
        required: false
        default: 'APP_VERSION'
        type: string
      DOCKER_BUILD_ARGS:
        description: 'Docker build arguments (format: VAR=value)'
        required: false
        type: string
    secrets:
      DOPPLER_TOKEN:
        description: 'Doppler token'
        required: false

jobs:
  aws-ecs-deploy:
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-session-name: ${{ github.event.repository.name }}-ci
          
      - name: Install Doppler CLI
        if: ${{ inputs.DOPPLER_DOWNLOAD_SECRETS }}
        uses: dopplerhq/cli-action@v2
      - name: Download secrets from Doppler
        if: ${{ inputs.DOPPLER_DOWNLOAD_SECRETS }}
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_CONFIG: ${{ vars.DOPPLER_CONFIG }}
          DOPPLER_PROJECT: ${{ vars.DOPPLER_PROJECT }}
        run: doppler secrets download --no-file --format env > .env
      - name: Add version to .env file
        run: |
          echo "${{ inputs.VERSION_VARIABLE_NAME }}=1.1.${{ github.run_number }}" >> .env
          
      - name: Build Docker image
        run: |
          # Start with base build command
          BUILD_CMD="docker build --build-arg uid=1000"
          
          # Add build arguments if provided
          if [ -n "${{ inputs.DOCKER_BUILD_ARGS }}" ]; then
            while IFS= read -r line; do
              # Skip empty lines
              if [ -n "$line" ]; then
                BUILD_CMD="$BUILD_CMD --build-arg $line"
              fi
            done <<< "${{ inputs.DOCKER_BUILD_ARGS }}"
          fi
          
          # Complete the build command
          BUILD_CMD="$BUILD_CMD -t app:latest ."
          
          # Execute the build command
          echo "Executing: $BUILD_CMD"
          eval $BUILD_CMD
        
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Tag Docker image
        run: |
          docker tag app:latest ${{ vars.ECR_URL }}/${{ vars.ECR_REPOSITORY }}:latest
          docker tag app:latest ${{ vars.ECR_URL }}/${{ vars.ECR_REPOSITORY }}:${{ github.run_number }}
          
      - name: Push Docker image
        run: |
          docker push ${{ vars.ECR_URL }}/${{ vars.ECR_REPOSITORY }}:latest
          docker push ${{ vars.ECR_URL }}/${{ vars.ECR_REPOSITORY }}:${{ github.run_number }}
          
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER_NAME }} --service ${{ vars.ECS_SERVICE_NAME }} --force-new-deployment --region ${{ inputs.AWS_REGION }}
